### ISSUE TITLE
Lot of information as input which might not be required

### ISSUE THREAD

**Issue by harshild** [messenger4j/messenger4j#1]
I was trying thing out. But some fields should not be required ideally just for simple message echoing.

- Callback Request Payload
- X-Hub-Signature
- APP SECRET

I have recently been engaging with end to end facebook bot services, they don't require all these parameters.

Also, i have developed a node.js code where i don't require such parameters.

I think there must be a way to bypass these in JAVA too. :)

**Comment by maxgrabenhorst** [comment]
Thanks for your feedback!

For testing purposes you can just provide arbitrary strings for `APP SECRET` and `VERIFY TOKEN` on `MessengerReceiveClientBuilder` construction. Then you can disable the signature verification and call the `processCallbackPayload` method without a signature:
```java
MessengerReceiveClient receiveClient = MessengerPlatform.newReceiveClientBuilder("APP_SECRET", "VERIFICATION_TOKEN")
                .disableSignatureVerification()
                .onTextMessageEvent(event ->  System.out.printf("%s: %s", event.getSender().getId(), event.getText()))
                .build();
        
receiveClient.processCallbackPayload(payload);
```
Does this solution solve your problem?

Since you know all these tokens I think it is a good practice to require them, because they are necessary for production use. In addition it should not be too easy to disable security features.

**Comment by maxgrabenhorst** [comment]
@harshild can I close this issue? Do you have any further questions or comments on this?

**Comment by harshild** [comment]
Yes sure :)
