### ISSUE TITLE
Jackson as json serialization toolkit

### ISSUE THREAD

**Issue by ginccc** [messenger4j/messenger4j#13]
Would be nice to be able to plug in another Json toolkit instead of gson

**Comment by maxgrabenhorst** [comment]
I agree that a pluggable json framework would be useful for some people. 
But since there are some framework specific annotations required at the moment (`@SerializedName`) that could be challenging.
One solution could be to define a custom annotation that indicates that the field name of a member should be overridden with a provided name, and that an implementation of a pluggable JSON-Serializer is aware of this annotation and uses it.
In addition the whole deserialization relies heavily on GSON.
Any ideas and / or PR is very welcome.

**Comment by hurelhuyag** [comment]
use both @SerializedName with @JsonProperty annotations.
