### ISSUE TITLE
Event classes should have a public constructor (or not be final)

### ISSUE THREAD

**Issue by jzarnikov** [messenger4j/messenger4j#2]
Event classes (e.g. com.github.messenger4j.receive.events.OptInEvent) is final and has only a private constructor.

This makes testing impossible. For example I have a class that implements com.github.messenger4j.receive.handlers.OptInEventHandler but I cannot write a junit test for it because I cannot easily create an instance of com.github.messenger4j.receive.events.OptInEvent in my test.

**Comment by maxgrabenhorst** [comment]
Thanks for your valuable feedback!

You are right that the current implementation makes unit testing hard. That should be changed.
I think it's a good solution to make the private constructors of the event classes public (be aware of inner classes that have to be changed too, e.g. `Attachment` in `AttachmentMessageEvent`). 

But the event classes should be final. I think there is no reason to derive classes from the existing event classes, because they implement / are part of the spec.

What do you think?

**Comment by maxgrabenhorst** [comment]
PR accepted - thanks Jan for your contribution.
