### ISSUE TITLE
Introduce an async API based on Vert.x 

### ISSUE THREAD

**Issue by sebastienblanc** [messenger4j/messenger4j#20]
Hi,

Thanks for this really nice project. 
What would you think to add support for an async API ? It could be based on vert.x and I know the team would be interested in it.

**Comment by maxgrabenhorst** [comment]
Hi, thank you. 
Really appreciate that you like the project.

I already considered to provide an async API and basically I think that's a really good idea.
But I want to prevent vendor lock-in and actually don't want to force the users to depend on a specific reactive framework. 

Nevertheless I'm open for discussions. I will evaluate what it would mean for messenger4j to provide  an async API based on vert.x and which approaches exist. I would be happy if you could provide me a vert.x contact in case of questions.

Thank you 👍

**Comment by sebastienblanc** [comment]
Hi ! Sorry for the late reply, yes I understand that you don't want a vendor lock-in but with @vietj from the vert.x team we were more thinking of a "plugin" system where you could pick the http provider you want.

**Comment by maxgrabenhorst** [comment]
Hi,
thanks for your reply and the suggestion of a "plugin" system.
Since I'm currently in the hot phase of my wedding preparation my spare time is quite rare.
I think I will get back to you by mid of August with a proposal of how this could be implemented.
I would appreciate your (and @vietj) feedback on the design of an async API for messenger4j.
