### ISSUE TITLE
Get facebook name of user

### ISSUE THREAD

**Issue by brunodeandrade** [messenger4j/messenger4j#26]
How can I get the facebook user name of an incoming message by the API?

**Comment by maxgrabenhorst** [comment]
Hi,
you can do it like this:
```java
final UserProfileClient userProfileClient = MessengerPlatform.newUserProfileClientBuilder(pageAccessToken).build();
final UserProfile userProfile = userProfileClient.queryUserProfile(userId);
final String firstName = userProfile.getFirstName();
final String lastName = userProfile.getLastName();
```

**Comment by brunodeandrade** [comment]
Thank you very much! It worked perfectly! :)

**Comment by brunodeandrade** [comment]
Sorry for reopen this issue, but how can I get the user name that is found on the url (ex: www.fb.com/user name.php)

**Comment by clamey** [comment]
Each Messenger app has it's own set of app-scoped IDs that it uses for users, which are separate from other apps and the main FB IDs:

https://developers.facebook.com/docs/messenger-platform/connecting-accounts

If your page and app have the same business owner in the FB Business Manager, you can use the ids_for_apps edge to get the other app-scoped IDs for that user.  I think you can then use that in a www.facebook.com/$ID URL (the messenger IDs don't work because they're limited in scope).

I don't see access to that user edge in this project, but it's easy enough to add in - maybe copy the user.UserProfile* classes to user.UserAppIDs* or something and then add a 'newUserAppIDsClientBuilder' entry point in MessengerPlatform...and then the 'appsecret_proof' query param would be a new thing as well:

https://developers.facebook.com/docs/graph-api/securing-requests

**Comment by maxgrabenhorst** [comment]
I will take a look at this and proof if m4j should support such a feature.

**Comment by maxgrabenhorst** [comment]
I created a follow up issue for this feature request (#40)
