### ISSUE TITLE
Proposal for a different domain object building approach

### ISSUE THREAD

**Issue by Pozo** [messenger4j/messenger4j#59]
Right now if you want to create an element for a **GenericTemplate** you write down something like this:

```
Element.create(
  "touch",
  of("Your Hands, Now in VR"),
  of(new URL("https://www.oculus.com/en-us/touch/")),
  empty(),
  of(touchButtons)
)
```
However I think there is a few issue with the example above.

- Needing to pack an argument in an **Optional**, is suboptimal for the compiler, and does an unnecessary wrapping. [1]
- **Optional** was designed to provide a limited mechanism for library method return types where there needed to be a clear way to represent "no result" [2]
- If there is a multiple arguments with the same type I must check the signature every time to be sure that I'm passing the value to the correct position
- After a while a can't be sure what's represent the empty() value

In order to make the domain object building logic more readable and avoid using **Optional** as a parameter, I'm suggesting that we should use builders for each domain object as follows:

E.g. In case of **Element**:

 - **ElementBuilder** class exists next to the **Element** class ( within the same package, but it might be nested as well )
 - **ElementBuilder** must has a package private constructor
 - **Element** class has a static method called builder which passes every mandatory arguments to the **ElementBuilder** constructor
 - **ElementBuilder** constructor holds arguments for the mandatory parameters for the facebook API, ( in case of **Element** the title mandatory for the API )
 - **ElementBuilder** constructor argument can be annotated with **@NonNull** so there will be the fail fast mechanism
 - **ElementBuilder** setters are for optional parameters in terms of facebook API

Then we can write down the following if we need only the bare minimum for an **Element**:
```
final Element element = Element.builder("Welcome to Peters Hats")
    .createElement()`
```
Or if we want represent more optional parameter:

```
final Element element = Element.builder("Welcome to Peters Hats")
    .setSubtitle("We have got the right hat for everyone.")
    .setImageUrl(new URL("https://petersfancybrownhats.com/company_image.png"))
    .setDefaultAction(defaultAction)
    .setButtons(buttons)
    .createElement();
```

The full functioning **ElementBuilder** can be found here : https://github.com/Pozo/messenger4j/commit/39c236e56d1cd842861dcfd720748d0be08a85d6

 - [1]  [Why should Java 8's Optional not be used in arguments](https://stackoverflow.com/a/39005452)
 - [2] [Optional used as field or parameter type](https://github.com/JetBrains/intellij-community/blob/master/plugins/InspectionGadgets/src/inspectionDescriptions/OptionalUsedAsFieldOrParameterType.html)

What do you think ?

**Comment by maxgrabenhorst** [comment]
Hi Zoltan,
thanks for your effort writing down your proposal in detail and providing an example.
I was pretty sure that someone will challenge the design decision to use `Optional` as parameters :)

In fact when I was redesigning the library this was the hardest decision for me.
In the previous version 0.8.0 the object construction was implemented as you described but I was not so happy with it. This had a few reasons:
* Extendability / maintainability: with this approach there is much more code to write / to adapt if the API changes or new features are added. Actually twice as much.
* Readability / Verbosity: Modeling the required parameters as constructor arguments is a must-have but required the user to lookup javadoc, whereas the optional attributes are described by the `set` methods of the builder. This is somehow a break. Additionally the usage of a lot of `set` methods could be very verbose. In most cases when reading the code you know what parameter is what because of the passing argument.
* Nested fluent builders: I designed a lot of builders as nested fluent builders which turned out for me to not work very well. This made using, reading and especially reusing thing hard or impossible.

On the other hand I know the downsides of using Optionals the way they are used right now and also the discussion around it.

To make it short: 
I suggest that you implement your approach for the use-case of sending `ReceiptTemplate` (see `com.github.messenger4j.test.integration.SendTest#shouldSendReceiptTemplateMessage`), and if you like for `com.github.messenger4j.test.integration.SendTest#shouldSendListTemplateMessage`.

Then we can compare the two solutions.
The outcome could be the following:
* stay with the `Optional` approach
* completely change to the builder pattern
* both approaches in parallel 
* both approaches in parallel for some objects

What do you think?

**Comment by Pozo** [comment]
This comparing approach sounds fair :) I'll work on that as soon as I can.

**Comment by maxgrabenhorst** [comment]
Closed due to no response. Please feel free to reopen.
